### ISSUE TITLE
Please implement plotting!

### ISSUE THREAD

**Issue by MDrueke** [JorritMontijn/zetapy#4]
I'd love to use the plotting functions in getZeta(). Would greatly appreciate it if you found the time to implement them.

**Comment by JorritMontijn** [comment]
Hi MDrueke, thank you for your feedback. Our python chief Guido is on it! We'll be porting other updates from https://github.com/JorritMontijn/zetatest as well, including some small improvements to the zeta-test (more stable resamplings, time-stitching) as well as the time-series version of the zeta-test you can use for things like calcium imaging. Since this is a pretty big update, it might take a while though, so Guido is in a better position to estimate when this might be finished

**Comment by guidomeijer** [comment]
The plotting has been ported to python! Pull the latest changes or pip install the latest zetapy version (2.7). 

The time series version will take a bit more time to implement, I aim to have it done in a month time.
